<?php
/**
* Import SPARES table from an EXCEL generated by SAP
* 
* @author  Werner Huysmans 
* @access  public
* @package warehouse
* @subpackage import
* @filesource* 
*/
error_reporting(E_ALL ^ E_NOTICE);
ini_set('memory_limit', '1024M');
define("INIT",true);

function import_action($inputFileName) {
    require("../includes/config_mycmms.inc.php");
    set_time_limit(0);
    date_default_timezone_set('Europe/London');

    $DB=DBC::get();
    if (INIT) {
        DBC::execute("DELETE FROM spares",array());
    }
    /** PHPExcel */
    require_once 'EXCEL_TOOLS/Classes/PHPExcel/IOFactory.php';
    $inputFileType="Excel2007";
    $objReader = PHPExcel_IOFactory::createReader($inputFileType); 
    $objPHPExcel = $objReader->load($doc_paths['import'].$inputFileName); 
    $objWorksheet = $objPHPExcel->getActiveSheet();
    $highestRow = $objWorksheet->getHighestRow(); // e.g. 10
    $highestColumn = $objWorksheet->getHighestColumn(); // e.g 'F'
    $highestColumnIndex = PHPExcel_Cell::columnIndexFromString($highestColumn); // e.g. 5
/**
* Adressing columns happens with letters, the array will translate a column(1) into A
*/
    $alphabet=array("A","B","C","D","E",
                    "F","G","H","I","J",
                    "K","L","M","N","O",
                    "P","Q","R","S","T");
    $cellvalues=array();
    $bom=array();

/**
* Loop through all rows in the Excel sheet
*/
    for ($i=2; $i<=$highestRow; $i++) {
        for ($j=0; $j<=15; $j++) {
            $value_of_cell=$objWorksheet->getCell($alphabet[$j].$i)->getValue();            
/**
* SAP identifies Functional Locations='7000*' 
* SAP identifies Equipments='3XXXX'
* SAP identifies Spares='540' 
* 
* When we discover a BOM container, we save it and trigger the search for spares
* This function "simplifies" the tree, the last BOM found is considered to be the BOM             
*/

            if (strlen($value_of_cell)==4 OR
                strlen($value_of_cell)==5 OR 
                substr($value_of_cell,0,4)=="7000") {
                $thebom=$value_of_cell;    
                break;
            }
            if (substr($value_of_cell,0,3)=="540") {   // Start looking for spares
                $itemnum=$value_of_cell;                
                try {
                    $DB->beginTransaction();
                    DBC::execute("INSERT IGNORE INTO spares (ID,SPARECODE,ITEMNUM,QTY) VALUES (NULL,:sparecode,:itemnum,1)",
                    array(
                        "sparecode"=>$thebom,
                        "itemnum"=>$itemnum));
                    $DB->commit();
                } catch (Exception $e) {
                    $DB->rollBack();
                    PDO_log($e,"Error in line $i");
                }
            }
        } // Check a line
    } // EO loop
        
/** SMARTY */
    require("setup.php");
    $tpl=new smarty_mycmms();
    $tpl->caching=false;
    $tpl->assign("stylesheet",STYLE_PATH."/".CSS_SMARTY);
    $tpl->assign("HROW",$highestRow);
    $tpl->assign("HCOL",$highestColumn);
    $tpl->assign("TEST",$cellvalues);
    $tpl->assign("excel_filename",$excel_filename);
    $tpl->assign("equipments",$equipments);
    $tpl->assign("wikipage","No WIKI information available");
    $tpl->display_error("import_bom.tpl");  
}
?>
