<?php
/**
* Import SPARES table from an EXCEL generated by SAP
* 
* @author  Werner Huysmans 
* @access  public
* @package warehouse
* @subpackage import
* @filesource
* CVS
* $Id: import_bom_sap.php,v 1.2 2013/08/07 11:10:11 werner Exp $
* $Source: /var/www/cvs/mycmms40/mycmms40/actions/import_bom_sap.php,v $
* $Log: import_bom_sap.php,v $
* Revision 1.2  2013/08/07 11:10:11  werner
* DEMB function for importing SAP BOM list:
* - 7000xxxx = standard
* - 540xxxxx = ASSY
* 
*/
error_reporting(E_ALL ^ E_NOTICE);
define("INIT",true);   # As STANDARD we do not ERASE the spares table

function import_action($inputFileName) {
    require("../includes/config_mycmms.inc.php");
    set_time_limit(0);
    date_default_timezone_set('Europe/London');
    
    $DB=DBC::get();
    if (INIT) {
        DBC::execute("DELETE FROM spares; 
            ALTER TABLE `spares` AUTO_INCREMENT=1;",array());
    }
    $temp_table="spares_sap";
    try {
        DBC::execute("CREATE TEMPORARY TABLE $temp_table(
            `ID` int(11) NOT NULL AUTO_INCREMENT,
            `SPARECODE` varchar(50) NOT NULL,
            `ITEMNUM` int(11) NOT NULL,
            `TYPE` char(20),
            `QTY` int(11),
            PRIMARY KEY (`ID`),
            UNIQUE KEY `BOM` (`SPARECODE`,`ITEMNUM`) USING BTREE
            ) ENGINE=MEMORY DEFAULT CHARSET=utf8;",array());
    } catch (Exception $e) {
        $DB->rollBack();
        PDO_log($e);
    }
    /** PHPExcel */
    require_once 'EXCEL_TOOLS/Classes/PHPExcel/IOFactory.php';
    $inputFileType="Excel2007";
    $objReader = PHPExcel_IOFactory::createReader($inputFileType); 
    $objPHPExcel = $objReader->load($doc_paths['import'].$inputFileName); 
    $objWorksheet = $objPHPExcel->getActiveSheet();
    $highestRow = $objWorksheet->getHighestRow(); // e.g. 10
    $highestColumn = $objWorksheet->getHighestColumn(); // e.g 'F'
    $highestColumnIndex = PHPExcel_Cell::columnIndexFromString($highestColumn); // e.g. 5

    $cellvalues=array();
    $bom=0; // BOM counter
    $spc=0;  // SPARE counter
/**
* Loop through all rows in the Excel sheet
*/
    for ($i=2; $i<=$highestRow; $i++) {
        $spares[$i]["SPARECODE"]= $objWorksheet->getCellByColumnAndRow(0,$i)->getValue();
        $spares[$i]["ITEMNUM"]=   $objWorksheet->getCellByColumnAndRow(2,$i)->getValue();
        if (substr($spares[$i]["SPARECODE"],0,3)=="540") {
            $spares[$i]["TYPE"]="SUBASSY";
        } else {
            $spares[$i]["TYPE"]="NORMAL";
        }
        try {
            $DB->beginTransaction();
            DBC::execute("INSERT IGNORE INTO spares_sap (ID,SPARECODE,ITEMNUM,TYPE,QTY) VALUES (NULL,:sparecode,:itemnum,:type,1)",
            array(
                "sparecode"=>   $spares[$i]["SPARECODE"],
                "itemnum"=>     $spares[$i]["ITEMNUM"],
                "type"=>        $spares[$i]["TYPE"]));
            $DB->commit();
        } catch (Exception $e) {
            $DB->rollBack();
                        
            PDO_log($e,"Error in line $i");
        }
    } // EO if
    try {
        $DB->beginTransaction();
        DBC::execute("INSERT IGNORE INTO spares SELECT * FROM spares_sap",array());
        DBC::execute("INSERT IGNORE INTO spares SELECT NULL,SPARECODE,ITEMNUM,TYPE,1 FROM spares_base",array());
        $result=$DB->query("SELECT DISTINCT SPARECODE FROM spares WHERE SPARECODE LIKE '540%'");
        $assys=$result->fetchAll(PDO::FETCH_ASSOC);
        foreach ($assys as $assy) {
            DBC::execute("UPDATE spares SET TYPE='ASSY' WHERE ITEMNUM='{$assy['SPARECODE']}'",array());
        }
        $DB->commit();
    } catch (Exception $e) {
        $DB->rollBack();
        PDO_log($e);
    }
    
        
/** SMARTY */
    require("setup.php");
    $tpl=new smarty_mycmms();
    $tpl->caching=false;
    $tpl->assign("stylesheet",STYLE_PATH."/".CSS_SMARTY);
    $tpl->assign("HROW",$highestRow);
    $tpl->assign("HCOL",$highestColumn);
    $tpl->assign("TEST",$cellvalues);
    $tpl->assign("excel_filename",$excel_filename);
    $tpl->assign("spares",$spares);
    $tpl->assign("wikipage","No WIKI information available");
    $tpl->display_error("import_bom_sap.tpl");  
}
?>
