<?php
/**
* Import SPARES table from an EXCEL generated by SAP
* 
* @author  Werner Huysmans 
* @access  public
* @package warehouse
* @subpackage import
* @filesource
* CVS
* $Id: import_bom_sap.php,v 1.2 2013/08/07 11:10:11 werner Exp $
* $Source: /var/www/cvs/mycmms40/mycmms40/actions/import_bom_sap.php,v $
* $Log: import_bom_sap.php,v $
* Revision 1.2  2013/08/07 11:10:11  werner
* DEMB function for importing SAP BOM list:
* - 7000xxxx = standard
* - 540xxxxx = ASSY
* 
*/
error_reporting(E_ALL ^ E_NOTICE);
define("INIT",false);   # As STANDARD we do not ERASE the spares table

function import_action($inputFileName) {
    require("../includes/config_mycmms.inc.php");
    DebugBreak();
    set_time_limit(0);
    date_default_timezone_set('Europe/London');
    
    $DB=DBC::get();
    if (INIT) { 
        /**
        * Initialisation routine
        */
    }
    $fh=fopen("tree.csv","w");
    /** PHPExcel */
    require_once 'EXCEL_TOOLS/Classes/PHPExcel/IOFactory.php';
    $inputFileType="Excel2007";
    $objReader = PHPExcel_IOFactory::createReader($inputFileType); 
    $objPHPExcel = $objReader->load($doc_paths['import'].$inputFileName); 
    $objWorksheet = $objPHPExcel->getActiveSheet();
    $highestRow = $objWorksheet->getHighestRow(); // e.g. 10
    $highestColumn = $objWorksheet->getHighestColumn(); // e.g 'F'
    $highestColumnIndex = PHPExcel_Cell::columnIndexFromString($highestColumn); // e.g. 5
    $cellvalues=array();
    $bom=0; // BOM counter
    $spc=0;  // SPARE counter
/**
* Create Output EXCEL Sheet    
*/
/**
    $objPHPExcelOut = new PHPExcel();
    $objPHPExcelOut->getProperties()->setCreator("Werner Huysmans")
                             ->setLastModifiedBy("Werner Huysmans")
                             ->setTitle("Office 2007 XLSX exported by myCMMS")
                             ->setSubject("Office 2007 XLSX content description")
                             ->setDescription("Exported by myCMMS.")
                             ->setKeywords("MYCMMS")
                             ->setCategory("MYCMMS EXPORT");
**/                             
/**
* Loop through all rows in the source Excel sheet
*/
    for ($i=2; $i<=$highestRow; $i++) {
        $data=array();
        $type="unknown";
        $parent="-";
        for ($j=1; $j<=40; $j++) {
            /**
            * Check if fields are empty, when not move to cells 1 and 3
            */
            if (!empty($objWorksheet->getCellByColumnAndRow($j,$i)->getValue())) {
                $data[]=$objWorksheet->getCellByColumnAndRow($j,$i)->getValue();    
/**
                DebugBreak();
                $objPHPExcelOut->setActiveSheetIndex(0)->setCellValue("A","X");
                $column++;                                                          
*/      
            }
            if (substr($data[0],0,2)=="BA") {  
                $type="FuncLoc"; 
                if (strlen($data[0])==9) {  $parent=substr($data[0],0,6);   }
                if (strlen($data[0])==13) {  $parent=substr($data[0],0,9);   }
                if (strlen($data[0])==17) {  $parent=substr($data[0],0,13);   }
                $last_FuncLoc=$data[0];
            }
                
            if (is_numeric($data[0]) AND $data[0] > 1000000) {  
                $type="Equipment"; 
                $parent=$last_FuncLoc;
                $last_Equipment=$data[0];
            }
            if (is_numeric($data[0]) AND $data[0] < 100000) {  
                $type="ASSY";
                $parent=$last_Equipment;
                $last_ASSY=$data[0];
            }
            if (is_numeric($data[0]) AND $data[0] > 100000 AND $data[0] < 500000) {  
                $type="PART"; 
                $parent=$last_Equipment;
            }
        }
        $SAP_data[$i]["EQNUM"]=$data[0];
        $SAP_data[$i]["PARENT"]=$parent;
        $SAP_data[$i]["DESCRIPTION"]=$data[1];
        $SAP_data[$i]["TYPE"]=$type;
        $sep=";";
        $csv=$data[0].$sep.$parent.$sep.$data[1].$sep.$type."\n";
#        DebugBreak();
        fwrite($fh,$csv);
    }
    fclose($fh);
/** SMARTY */
    require("setup.php");
    $tpl=new smarty_mycmms();
    $tpl->caching=false;
    $tpl->assign("stylesheet",STYLE_PATH."/".CSS_SMARTY);
    $tpl->assign("HROW",$highestRow);
    $tpl->assign("HCOL",$highestColumn);
    $tpl->assign("TEST",$cellvalues);
    $tpl->assign("excel_filename",$excel_filename);
    $tpl->assign("data",$SAP_data);
    $tpl->assign("wikipage","No WIKI information available");
    $tpl->display_error("import_sap_tree_step1.tpl");  
}
?>
